"""Curated Consist schemas for the SynthFirm teaching-slice outputs.

These SQLModel classes started from schema profiles captured in the Austin
Step 1-3 smoke run. They are intentionally narrow: they cover the main firm,
producer, wholesaler, consumer, and SCTG-partition outputs that best explain the
early SynthFirm pipeline.

The classes preserve the observed CSV column names with explicit SQLAlchemy
``Column`` definitions. Keep them as checked-in examples for downstream users:
export a schema stub from a new Consist run, edit only relationships and
descriptions you understand, then pass the class back to Consist when tagging
that artifact.
"""

from typing import Optional

from sqlalchemy import BigInteger, Column, Float, ForeignKey, String
from sqlmodel import Field, SQLModel


class SyntheticFirms(SQLModel, table=True):
    """Synthetic businesses generated by Step 1 before producer/consumer roles."""

    __tablename__ = "synthetic_firms"
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    CBPZONE: Optional[int] = Field(
        default=None,
        description="County Business Patterns zone for the firm.",
        sa_column=Column("CBPZONE", BigInteger(), nullable=True),
    )
    FAFZONE: Optional[int] = Field(
        default=None,
        description="Freight Analysis Framework zone for the firm.",
        sa_column=Column("FAFZONE", BigInteger(), nullable=True),
    )
    esizecat: Optional[int] = Field(
        default=None,
        description="Employment-size category assigned to the firm.",
        sa_column=Column("esizecat", BigInteger(), nullable=True),
    )
    Industry_NAICS6_Make: Optional[str] = Field(
        default=None,
        description="Six-digit NAICS make industry used for firm generation.",
        sa_column=Column("Industry_NAICS6_Make", String(), nullable=True),
    )
    Commodity_SCTG: Optional[int] = Field(
        default=None,
        description="SCTG commodity produced by the firm.",
        sa_column=Column("Commodity_SCTG", BigInteger(), nullable=True),
    )
    Emp: Optional[float] = Field(
        default=None,
        description="Synthetic employment assigned to the firm.",
        sa_column=Column("Emp", Float(), nullable=True),
    )
    BusID: Optional[int] = Field(
        default=None,
        description="Synthetic firm identifier used by downstream steps.",
        sa_column=Column("BusID", BigInteger(), nullable=True),
    )
    MESOZONE: Optional[int] = Field(
        default=None,
        description="Mesozone assigned to the firm.",
        sa_column=Column("MESOZONE", BigInteger(), nullable=True),
    )
    ZIPCODE: Optional[int] = Field(
        default=None,
        description="ZIP code assigned to the firm.",
        sa_column=Column("ZIPCODE", BigInteger(), nullable=True),
    )


class SyntheticProducers(SQLModel, table=True):
    """Producer-side firm output generated from Step 1 synthetic firms."""

    __tablename__ = "synthetic_producers"
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    SellerID: Optional[int] = Field(
        default=None,
        description="Synthetic firm identifier for the seller.",
        sa_column=Column(
            "SellerID",
            BigInteger(),
            ForeignKey("synthetic_firms.BusID"),
            nullable=True,
        ),
    )
    Zone: Optional[int] = Field(
        default=None,
        description="Mesozone or production zone for the seller.",
        sa_column=Column("Zone", BigInteger(), nullable=True),
    )
    NAICS: Optional[str] = Field(
        default=None,
        description="Seller industry code used in producer generation.",
        sa_column=Column("NAICS", String(), nullable=True),
    )
    Commodity_SCTG: Optional[int] = Field(
        default=None,
        description="SCTG commodity produced by the seller.",
        sa_column=Column("Commodity_SCTG", BigInteger(), nullable=True),
    )
    Size: Optional[float] = Field(
        default=None,
        description="Producer employment or size value carried into Step 2.",
        sa_column=Column("Size", Float(), nullable=True),
    )
    OutputCapacitylb: Optional[float] = Field(
        default=None,
        description="Estimated output capacity in pounds.",
        sa_column=Column("OutputCapacitylb", Float(), nullable=True),
    )
    NonTransportUnitCost: Optional[float] = Field(
        default=None,
        description="Estimated commodity unit cost before transportation costs.",
        sa_column=Column("NonTransportUnitCost", Float(), nullable=True),
    )


class SyntheticWholesalers(SQLModel, table=True):
    """Wholesaler records generated alongside producers in Step 2."""

    __tablename__ = "synthetic_wholesalers"
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    index: Optional[int] = Field(
        default=None,
        description="Row index emitted by the Step 2 wholesaler output.",
        sa_column=Column("index", BigInteger(), nullable=True),
    )
    CBPZONE: Optional[int] = Field(
        default=None,
        description="County Business Patterns zone for the wholesaler.",
        sa_column=Column("CBPZONE", BigInteger(), nullable=True),
    )
    FAFZONE: Optional[int] = Field(
        default=None,
        description="Freight Analysis Framework zone for the wholesaler.",
        sa_column=Column("FAFZONE", BigInteger(), nullable=True),
    )
    esizecat: Optional[int] = Field(
        default=None,
        description="Employment-size category for the wholesaler.",
        sa_column=Column("esizecat", BigInteger(), nullable=True),
    )
    NAICS: Optional[int] = Field(
        default=None,
        description="Observed wholesaler NAICS code.",
        sa_column=Column("NAICS", BigInteger(), nullable=True),
    )
    Size: Optional[float] = Field(
        default=None,
        description="Wholesaler employment or size value.",
        sa_column=Column("Size", Float(), nullable=True),
    )
    SellerID: Optional[int] = Field(
        default=None,
        description="Synthetic firm identifier for the wholesaler seller.",
        sa_column=Column(
            "SellerID",
            BigInteger(),
            ForeignKey("synthetic_firms.BusID"),
            nullable=True,
        ),
    )
    Zone: Optional[int] = Field(
        default=None,
        description="Mesozone or activity zone for the wholesaler.",
        sa_column=Column("Zone", BigInteger(), nullable=True),
    )
    ZIPCODE: Optional[int] = Field(
        default=None,
        description="ZIP code assigned to the wholesaler.",
        sa_column=Column("ZIPCODE", BigInteger(), nullable=True),
    )
    InputCommodity: Optional[str] = Field(
        default=None,
        description="Input commodity or industry consumed by the wholesaler.",
        sa_column=Column("InputCommodity", String(), nullable=True),
    )
    Commodity_SCTG: Optional[int] = Field(
        default=None,
        description="SCTG commodity handled by the wholesaler.",
        sa_column=Column("Commodity_SCTG", BigInteger(), nullable=True),
    )
    ValEmp: Optional[float] = Field(
        default=None,
        description="Value per employee used to estimate wholesaler output.",
        sa_column=Column("ValEmp", Float(), nullable=True),
    )
    ProdVal: Optional[float] = Field(
        default=None,
        description="Estimated production value for the wholesaler.",
        sa_column=Column("ProdVal", Float(), nullable=True),
    )
    NonTransportUnitCost: Optional[float] = Field(
        default=None,
        description="Estimated commodity unit cost before transportation costs.",
        sa_column=Column("NonTransportUnitCost", Float(), nullable=True),
    )
    OutputCapacitylb: Optional[float] = Field(
        default=None,
        description="Estimated wholesaler output capacity in pounds.",
        sa_column=Column("OutputCapacitylb", Float(), nullable=True),
    )


class IoSummary(SQLModel, table=True):
    """Make-use industry summary generated by Step 2."""

    __tablename__ = "io_summary"
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    Industry_NAICS6_Make: Optional[str] = Field(
        default=None,
        description="Six-digit NAICS make industry.",
        sa_column=Column("Industry_NAICS6_Make", String(), nullable=True),
    )
    Industry_NAICS6_Use: Optional[str] = Field(
        default=None,
        description="Six-digit NAICS use industry.",
        sa_column=Column("Industry_NAICS6_Use", String(), nullable=True),
    )
    ProVal: Optional[float] = Field(
        default=None,
        description="Production value linking make and use industries.",
        sa_column=Column("ProVal", Float(), nullable=True),
    )


class SyntheticConsumers(SQLModel, table=True):
    """Consumer-side demand records generated in Step 3."""

    __tablename__ = "synthetic_consumers"
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    NAICS: Optional[str] = Field(
        default=None,
        description="Buyer industry code used in consumer generation.",
        sa_column=Column("NAICS", String(), nullable=True),
    )
    InputCommodity: Optional[str] = Field(
        default=None,
        description="Input commodity or industry required by the buyer.",
        sa_column=Column("InputCommodity", String(), nullable=True),
    )
    Commodity_SCTG: Optional[int] = Field(
        default=None,
        description="SCTG commodity purchased by the buyer.",
        sa_column=Column("Commodity_SCTG", BigInteger(), nullable=True),
    )
    Zone: Optional[int] = Field(
        default=None,
        description="Mesozone or activity zone for the buyer.",
        sa_column=Column("Zone", BigInteger(), nullable=True),
    )
    buyer_sctg: Optional[int] = Field(
        default=None,
        description="SCTG group label emitted for the buyer record.",
        sa_column=Column("Buyer.SCTG", BigInteger(), nullable=True),
    )
    BuyerID: Optional[int] = Field(
        default=None,
        description="Synthetic firm identifier for the buyer.",
        sa_column=Column(
            "BuyerID",
            BigInteger(),
            ForeignKey("synthetic_firms.BusID"),
            nullable=True,
        ),
    )
    Size: Optional[float] = Field(
        default=None,
        description="Buyer employment or size value.",
        sa_column=Column("Size", Float(), nullable=True),
    )
    ConVal: Optional[float] = Field(
        default=None,
        description="Estimated consumption value for the buyer.",
        sa_column=Column("ConVal", Float(), nullable=True),
    )
    PurchaseAmountlb: Optional[float] = Field(
        default=None,
        description="Estimated purchase amount in pounds.",
        sa_column=Column("PurchaseAmountlb", Float(), nullable=True),
    )


class ProducersBySctg(SQLModel, table=True):
    """Per-SCTG producer partition rows from the Step 2 OutputSet."""

    __tablename__ = "producers_by_sctg"
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    SCTG_Group: Optional[int] = Field(
        default=None,
        description="SCTG group represented by this partition row.",
        sa_column=Column("SCTG_Group", BigInteger(), nullable=True),
    )
    Commodity_SCTG: Optional[int] = Field(
        default=None,
        description="SCTG commodity produced by the seller.",
        sa_column=Column("Commodity_SCTG", BigInteger(), nullable=True),
    )
    SellerID: Optional[int] = Field(
        default=None,
        description="Producer seller identifier.",
        sa_column=Column(
            "SellerID",
            BigInteger(),
            ForeignKey("synthetic_producers.SellerID"),
            nullable=True,
        ),
    )
    Zone: Optional[int] = Field(
        default=None,
        description="Mesozone or production zone for the seller.",
        sa_column=Column("Zone", BigInteger(), nullable=True),
    )
    NAICS: Optional[str] = Field(
        default=None,
        description="Seller industry code.",
        sa_column=Column("NAICS", String(), nullable=True),
    )
    Size: Optional[float] = Field(
        default=None,
        description="Producer employment or size value.",
        sa_column=Column("Size", Float(), nullable=True),
    )
    OutputCapacitylb: Optional[float] = Field(
        default=None,
        description="Estimated output capacity in pounds.",
        sa_column=Column("OutputCapacitylb", Float(), nullable=True),
    )
    NonTransportUnitCost: Optional[float] = Field(
        default=None,
        description="Estimated commodity unit cost before transportation costs.",
        sa_column=Column("NonTransportUnitCost", Float(), nullable=True),
    )


class ConsumersBySctg(SQLModel, table=True):
    """Per-SCTG consumer partition rows from the Step 3 OutputSet."""

    __tablename__ = "consumers_by_sctg"
    __table_args__ = {"extend_existing": True}
    __abstract__ = True

    SCTG_Group: Optional[int] = Field(
        default=None,
        description="SCTG group represented by this partition row.",
        sa_column=Column("SCTG_Group", BigInteger(), nullable=True),
    )
    Commodity_SCTG: Optional[int] = Field(
        default=None,
        description="SCTG commodity purchased by the buyer.",
        sa_column=Column("Commodity_SCTG", BigInteger(), nullable=True),
    )
    BuyerID: Optional[int] = Field(
        default=None,
        description="Consumer buyer identifier.",
        sa_column=Column(
            "BuyerID",
            BigInteger(),
            ForeignKey("synthetic_consumers.BuyerID"),
            nullable=True,
        ),
    )
    Zone: Optional[int] = Field(
        default=None,
        description="Mesozone or activity zone for the buyer.",
        sa_column=Column("Zone", BigInteger(), nullable=True),
    )
    NAICS: Optional[str] = Field(
        default=None,
        description="Buyer industry code.",
        sa_column=Column("NAICS", String(), nullable=True),
    )
    InputCommodity: Optional[str] = Field(
        default=None,
        description="Input commodity or industry required by the buyer.",
        sa_column=Column("InputCommodity", String(), nullable=True),
    )
    PurchaseAmountlb: Optional[float] = Field(
        default=None,
        description="Estimated purchase amount in pounds.",
        sa_column=Column("PurchaseAmountlb", Float(), nullable=True),
    )


SYNTHFIRM_CONSIST_SCHEMAS = (
    SyntheticFirms,
    SyntheticProducers,
    SyntheticWholesalers,
    IoSummary,
    SyntheticConsumers,
    ProducersBySctg,
    ConsumersBySctg,
)
